---
argument_specs:
  main:
    options:
      authorized_ssh_keys:
        type: list
        required: false
        default: []
        description: |
          A list of authorized SSH keys. Each list element is a dict with the following keys:
          - key: The SSH key to add
          - users: The users to add the key to
