---
- name: create app directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
  with_items:
    - /opt/apps
    - "/opt/apps/{{app_service_name}}"

- name: configure nginx
  template:
    src: server.conf.j2
    dest: "/etc/nginx/sites-enabled/{{app_service_name}}"
  notify: restart nginx

- name: install jq and unzip used in react app deploy script
  apt:
    name: "{{item}}"
    update_cache: true
    cache_valid_time: 86400
  with_items:
    - jq
    - unzip
