- name: create folder ssl
  file: path={{ nginx_path }}/ssl state=directory

- name: create dhparams file if needed
  command: openssl dhparam -out {{ dhparam_path }} 1024
  args:
    creates: "{{dhparam_path}}"
  notify:
    - check nginx conf
    - restart nginx

- name: create dhparams 2048 file if needed
  command: openssl dhparam -out {{ dhparam_path_2048 }} 2048
  args:
    creates: "{{dhparam_path_2048}}"
  notify:
    - check nginx conf
    - restart nginx

- include: self-signed.yml
  when: ssl_strategy == 'self-signed'

- include_role:
    name: ansible-letsencrypt
  vars:
    letsencrypt_email: contact@particulier.api.gouv.fr
    letsencrypt_cert_domains:
      - "{{ server_name }}"
    letsencrypt_renewal_command_args: '--renew-hook "systemctl restart nginx"'
  when: ssl_strategy == 'certbot'
