- name: Install OVH DNS plugins
  apt:
    name:
      - python3-certbot-nginx
      - python3-certbot-dns-ovh

- name: Create directory for OVH DNS API secret files
  file:
    path: /etc/letsencrypt/ovh-dns-secrets
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Install OVH DNS API secrets file for ovh_zone
  template:
    dest: "/etc/letsencrypt/ovh-dns-secrets/{{ ssl_ovh_zone }}.ini"
    src: ovh-secrets.ini.j2
    owner: root
    group: root
    mode: 0600

- name: Install, configure and run certbot
  include_role:
    name: geerlingguy.certbot
  vars:
    certbot_auto_renew_user: "{{ ssl_certbot_auto_renew_user }}"
    certbot_auto_renew_minute: "{{ ssl_certbot_auto_renew_minute }}"
    certbot_auto_renew_hour: "{{ ssl_certbot_auto_renew_hour }}"
    certbot_admin_email: "{{ ssl_certbot_admin_email }}"
    certbot_create_if_missing: "{{ ssl_certbot_create_if_missing }}"
    certbot_create_command: "{{ certbot_script }} certonly --dns-ovh --dns-ovh-credentials /etc/letsencrypt/ovh-dns-secrets/{{ ssl_ovh_zone }}.ini --dns-ovh-propagation-seconds {{ ssl_ovh_propagation_seconds }} --noninteractive --agree-tos --email {{ cert_item.email | default(certbot_admin_email) }} -d {{ cert_item.domains | join(',') }} --expand"
    certbot_certs: "{{ ssl_certbot_certs }}"

- name: Reload nginx after certificate installation
  service:
    name: nginx
    state: reloaded
