- name: Install OVH DNS plugins
  apt:
    name:
      - python3-certbot-nginx
      - python3-certbot-dns-ovh

- name: Create directory for OVH DNS API secret files
  file:
    path: /etc/letsencrypt/ovh-dns-secrets
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Install OVH DNS API secrets file for ovh_zone
  template:
    dest: "/etc/letsencrypt/ovh-dns-secrets/{{ ovh_zone }}.ini"
    src: ovh-secrets.ini.j2
    owner: root
    group: root
    mode: 0600

- name: Install, configure and run certbot
  include_role:
    name: geerlingguy.certbot

- name: Reload nginx after certificate installation
  service:
    name: nginx
    state: reloaded
