---
- name: Copy the deployment script
  template:
    src: deploy-dev.sh.j2
    dest: "{{ deployment_script_dir }}/deploy-dev.sh"
    owner: "{{ deployment_script_owner }}"
    group: "{{ deployment_script_owner }}"
    mode: 0755
