- name: install postgresql
  apt:
    name: "{{ item }}"
  with_items:
    - postgresql
    - python3-psycopg2

- name: create postgresql user
  postgresql_user:
    name: "{{ pg_user }}"
    password: "{{ pg_password }}"
  become_user: postgres

- name: create db
  postgresql_db:
    name: "{{ pg_database }}"
    owner: "{{ pg_user }}"
  become_user: postgres

- name: Adds extensions to the database
  postgresql_ext:
    name: "{{ item }}"
    db: "{{ pg_database }}"
    schema: public
  with_items:
    - "{{ pg_extensions }}"
  become_user: postgres
